### ISSUE TITLE
stream errors

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/traxsourcetagger#2] opened 2021-02-02 17:26 UTC
Hi, thank you for the Traxsource tagger!

After some testing i've found out that traxsource tagger is responsible for some stream errors in the files.
I've tested the files with 3 different programs.
Traxsource tagger is responsible for a null stream at the begging of the files.
Audio stream is not affected as far as i can tell!

![Screenshot 2021-02-02 191136](https://user-images.githubusercontent.com/74199552/106637067-35ebe680-657a-11eb-9384-8c94eb2f5d46.jpg)
![Screenshot 2021-02-02 191456](https://user-images.githubusercontent.com/74199552/106637082-371d1380-657a-11eb-9c99-85e4e555a015.jpg)
![Screenshot 2021-02-02 192832](https://user-images.githubusercontent.com/74199552/106638744-19e94480-657c-11eb-9544-bcfecdae8dc7.jpg)

**Comment by Marekkon5** [comment] 2021-02-03 21:17
Hello, the issue is with the underlying ID3 library. However the bug is kinda handled in safe manner, so it doesn't affect the actual audio or tags, so we didn't notice until now.
I've been trying to fix the issue and waiting for approval: https://github.com/polyfloyd/rust-id3/pull/56

However in any case it should be fixed within few days in this app (and Discogstagger too).

**Comment by rosgr100** [comment] 2021-02-04 12:27
Hi, @Marekkon5.

Thanks for the heads-up!

**Comment by Marekkon5** [comment] 2021-02-05 22:09
Should be fixed in the new release.

**Closed as completed by Marekkon5** 2021-02-05 22:09 UTC

**Comment by rosgr100** [comment] 2021-02-06 01:34
> Should be fixed in the new release.

It's fixed. 👍
Thank you for the effort!
